spring:
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    hikari:
      maximum-pool-size: 1
      maximum-idle: 1
  application:
    name: practica

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
